# GitHub Actions Workflow for Dev Environment Deployment
#
# IMPORTANT: This file needs to be manually moved to .github/workflows/deploy-dev.yml
# by the repository owner due to GitHub App workflow permissions.
#
# To enable this workflow:
#   1. Copy this file to: .github/workflows/deploy-dev.yml
#   2. Configure the required GitHub Secrets (see below)
#   3. Commit and push the changes
#
# Required GitHub Secrets:
#   - AZURE_CLIENT_ID: Azure service principal client ID
#   - AZURE_TENANT_ID: Azure tenant ID
#   - AZURE_SUBSCRIPTION_ID: Azure subscription ID
#   - SQL_ADMIN_LOGIN: SQL Server admin username (e.g., sqladmin)
#   - SQL_ADMIN_PASSWORD: SQL Server admin password (strong password required)

name: Deploy to Dev Environment

on:
  workflow_dispatch:
    inputs:
      skipInfra:
        description: 'Skip infrastructure deployment (only deploy app)'
        required: false
        type: boolean
        default: false

env:
  AZURE_RESOURCE_GROUP: shadowbrook-dev-rg
  AZURE_LOCATION: eastus
  ACR_NAME: shadowbrookacr
  IMAGE_NAME: shadowbrook

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create resource group
        run: |
          az group create \
            --name ${{ env.AZURE_RESOURCE_GROUP }} \
            --location ${{ env.AZURE_LOCATION }}

      - name: Create Azure Container Registry
        run: |
          if ! az acr show --name ${{ env.ACR_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} 2>/dev/null; then
            az acr create \
              --name ${{ env.ACR_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --sku Basic \
              --admin-enabled false
          fi

      - name: Build and push Docker image
        run: |
          az acr build \
            --registry ${{ env.ACR_NAME }} \
            --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --image ${{ env.IMAGE_NAME }}:latest \
            --file Dockerfile \
            .

      - name: Deploy infrastructure
        if: ${{ !inputs.skipInfra }}
        run: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file infra/bicep/main.bicep \
            --parameters environment=dev \
            --parameters location=${{ env.AZURE_LOCATION }} \
            --parameters sqlAdminLogin=${{ secrets.SQL_ADMIN_LOGIN }} \
            --parameters sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }} \
            --parameters acrName=${{ env.ACR_NAME }} \
            --parameters imageTag=${{ github.sha }}

      - name: Update container app (infrastructure already deployed)
        if: ${{ inputs.skipInfra }}
        run: |
          az containerapp update \
            --name shadowbrook-app-dev \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Grant ACR pull access to Container App
        run: |
          # Get Container App's managed identity principal ID
          PRINCIPAL_ID=$(az containerapp show \
            --name shadowbrook-app-dev \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query identity.principalId \
            --output tsv)

          # Get ACR resource ID
          ACR_ID=$(az acr show \
            --name ${{ env.ACR_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query id \
            --output tsv)

          # Assign AcrPull role to Container App identity
          az role assignment create \
            --assignee $PRINCIPAL_ID \
            --role AcrPull \
            --scope $ACR_ID

      - name: Run database migrations
        run: |
          # Get the app URL
          APP_URL=$(az containerapp show \
            --name shadowbrook-app-dev \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query properties.configuration.ingress.fqdn \
            --output tsv)

          echo "App deployed at: https://$APP_URL"

          # Wait for app to be ready
          echo "Waiting for app to be ready..."
          for i in {1..30}; do
            if curl -f -s "https://$APP_URL/health" > /dev/null 2>&1; then
              echo "App is ready!"
              break
            fi
            echo "Attempt $i: App not ready yet, waiting..."
            sleep 10
          done

      - name: Output deployment info
        run: |
          APP_URL=$(az containerapp show \
            --name shadowbrook-app-dev \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query properties.configuration.ingress.fqdn \
            --output tsv)

          SQL_SERVER=$(az sql server show \
            --name shadowbrook-sql-dev \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query fullyQualifiedDomainName \
            --output tsv)

          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **App URL:** https://$APP_URL" >> $GITHUB_STEP_SUMMARY
          echo "- **SQL Server:** $SQL_SERVER" >> $GITHUB_STEP_SUMMARY
          echo "- **Database:** shadowbrook-db-dev" >> $GITHUB_STEP_SUMMARY
          echo "- **Container Image:** ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Resource Group:** ${{ env.AZURE_RESOURCE_GROUP }}" >> $GITHUB_STEP_SUMMARY
