using System.Reflection;
using JasperFx.CodeGeneration;
using Microsoft.EntityFrameworkCore;
using Teeforce.Domain.Common;
using Wolverine;
using Wolverine.EntityFrameworkCore;
using Wolverine.ErrorHandling;
using Wolverine.FluentValidation;
using Wolverine.SqlServer;

namespace Teeforce.Api.Infrastructure;

public static class WolverineExtensions
{
    /// <summary>
    /// Detects whether the app was launched with <c>dotnet run -- codegen write</c>.
    /// Uses the same pattern recommended by the Wolverine docs.
    /// </summary>
    public static bool IsCodeGeneration()
    {
        return Assembly.GetEntryAssembly()?.GetName().Name == "GetDocument.Insider"
            || Environment.GetCommandLineArgs().Any(a => a.Equals("codegen", StringComparison.OrdinalIgnoreCase));
    }

    public static IHostBuilder AddWolverine(
        this IHostBuilder host,
        IHostEnvironment environment,
        IConfiguration configuration,
        string? connectionString)
    {
        if (IsCodeGeneration())
        {
            host.ConfigureServices(services =>
            {
                services.DisableAllExternalWolverineTransports();
                services.DisableAllWolverineMessagePersistence();
            });
        }

        host.UseWolverine(opts =>
        {
            opts.Discovery.IncludeAssembly(typeof(Program).Assembly);

            // Pre-generate handler code for deployed environments. Dynamic mode loads the
            // Roslyn compiler at runtime, consuming ~1 GB of native memory for in-memory
            // assembly emission that the GC cannot reclaim. Static mode uses pre-compiled
            // handler classes generated by `dotnet run -- codegen write`.
            // Development and Testing (integration tests) default to Dynamic. Override with
            // Wolverine:CodeGenMode=Static in appsettings or env vars.
            var configuredMode = configuration["Wolverine:CodeGenMode"];
            opts.CodeGeneration.TypeLoadMode = configuredMode is not null
                ? Enum.Parse<TypeLoadMode>(configuredMode, ignoreCase: true)
                : environment.IsDevelopment() || environment.IsEnvironment("Testing")
                    ? TypeLoadMode.Dynamic
                    : TypeLoadMode.Static;

            if (connectionString is not null)
            {
                // Increase command timeout for Wolverine transport provisioning — Azure SQL Basic tier
                // (5 DTU) is too slow for the default 30s timeout during schema migration.
                var wolverineConnectionString = new Microsoft.Data.SqlClient.SqlConnectionStringBuilder(connectionString)
                {
                    ConnectTimeout = 120,
                    CommandTimeout = 120
                }.ConnectionString;

#pragma warning disable CS0618 // EnableMessageTransport not implemented in 5.20.1
                opts.UseSqlServerPersistenceAndTransport(wolverineConnectionString, "wolverine")
                    .AutoProvision();
#pragma warning restore CS0618
            }

            opts.MultipleHandlerBehavior = MultipleHandlerBehavior.Separated;

            opts.OnException<DbUpdateConcurrencyException>()
                .RetryTimes(3);

            opts.UseEntityFrameworkCoreTransactions();
            opts.Policies.AutoApplyTransactions();
            opts.Policies.UseDurableLocalQueues();
            opts.UseFluentValidation();
            opts.PublishDomainEventsFromEntityFrameworkCore<Entity, IDomainEvent>(e => e.DomainEvents);
        });

        return host;
    }
}
