// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shadowbrook.Api.Infrastructure.Data;

#nullable disable

namespace Shadowbrook.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326135924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shadowbrook.Api.Features.Bookings.Policies.BookingConfirmationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BookingConfirmationPolicies", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Api.Features.Waitlist.Policies.TeeTimeOpeningExpirationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TeeTimeOpeningExpirationPolicies", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Api.Features.Waitlist.Policies.TeeTimeOpeningOfferPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PendingOfferCount")
                        .HasColumnType("int");

                    b.Property<int>("SlotsRemaining")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeeTimeOpeningOfferPolicies", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Api.Features.Waitlist.Policies.WaitlistOfferResponsePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpeningId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WaitlistOfferResponsePolicies", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Api.Infrastructure.Dev.DevSmsMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("DevSmsMessages", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.BookingAggregate.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GolferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GolferName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TeeTime", "Shadowbrook.Domain.BookingAggregate.Booking.TeeTime#TeeTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("Date");

                            b1.Property<TimeOnly>("Time")
                                .HasColumnType("time")
                                .HasColumnName("TeeTime");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.CourseAggregate.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeOnly?>("FirstTeeTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("FlatRatePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("LastTeeTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TeeTimeIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("WaitlistEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.CourseWaitlistAggregate.CourseWaitlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WaitlistType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Date")
                        .IsUnique();

                    b.ToTable("CourseWaitlists", (string)null);

                    b.HasDiscriminator<string>("WaitlistType").HasValue("CourseWaitlist");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shadowbrook.Domain.GolferAggregate.Golfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Golfers", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.GolferWaitlistEntryAggregate.GolferWaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseWaitlistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GolferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsWalkUp")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("WindowEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WindowStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GolferId");

                    b.HasIndex("CourseWaitlistId", "GolferId")
                        .IsUnique()
                        .HasFilter("[RemovedAt] IS NULL");

                    b.ToTable("GolferWaitlistEntries", (string)null);

                    b.HasDiscriminator<bool>("IsWalkUp");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shadowbrook.Domain.TeeTimeOpeningAggregate.TeeTimeOpening", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FilledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("OperatorOwned")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SlotsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("SlotsRemaining")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TeeTime", "Shadowbrook.Domain.TeeTimeOpeningAggregate.TeeTimeOpening.TeeTime#TeeTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("Date");

                            b1.Property<TimeOnly>("Time")
                                .HasColumnType("time")
                                .HasColumnName("TeeTime");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Status");

                    b.ToTable("TeeTimeOpenings", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.TenantAggregate.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationName")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.WaitlistOfferAggregate.WaitlistOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GolferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GolferWaitlistEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupSize")
                        .HasColumnType("int");

                    b.Property<bool>("IsWalkUp")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OpeningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OpeningId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("GolferWaitlistEntryId", "OpeningId");

                    b.ToTable("WaitlistOffers", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.CourseWaitlistAggregate.OnlineWaitlist", b =>
                {
                    b.HasBaseType("Shadowbrook.Domain.CourseWaitlistAggregate.CourseWaitlist");

                    b.HasDiscriminator().HasValue("Online");
                });

            modelBuilder.Entity("Shadowbrook.Domain.CourseWaitlistAggregate.WalkUpWaitlist", b =>
                {
                    b.HasBaseType("Shadowbrook.Domain.CourseWaitlistAggregate.CourseWaitlist");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasIndex("ShortCode", "Date");

                    b.HasDiscriminator().HasValue("WalkUp");
                });

            modelBuilder.Entity("Shadowbrook.Domain.GolferWaitlistEntryAggregate.OnlineGolferWaitlistEntry", b =>
                {
                    b.HasBaseType("Shadowbrook.Domain.GolferWaitlistEntryAggregate.GolferWaitlistEntry");

                    b.HasDiscriminator().HasValue(false);
                });

            modelBuilder.Entity("Shadowbrook.Domain.GolferWaitlistEntryAggregate.WalkUpGolferWaitlistEntry", b =>
                {
                    b.HasBaseType("Shadowbrook.Domain.GolferWaitlistEntryAggregate.GolferWaitlistEntry");

                    b.HasDiscriminator().HasValue(true);
                });

            modelBuilder.Entity("Shadowbrook.Domain.CourseAggregate.Course", b =>
                {
                    b.HasOne("Shadowbrook.Domain.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shadowbrook.Domain.CourseWaitlistAggregate.CourseWaitlist", b =>
                {
                    b.HasOne("Shadowbrook.Domain.CourseAggregate.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shadowbrook.Domain.GolferWaitlistEntryAggregate.GolferWaitlistEntry", b =>
                {
                    b.HasOne("Shadowbrook.Domain.CourseWaitlistAggregate.CourseWaitlist", null)
                        .WithMany()
                        .HasForeignKey("CourseWaitlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shadowbrook.Domain.GolferAggregate.Golfer", null)
                        .WithMany()
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shadowbrook.Domain.TeeTimeOpeningAggregate.TeeTimeOpening", b =>
                {
                    b.HasOne("Shadowbrook.Domain.CourseAggregate.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shadowbrook.Domain.WaitlistOfferAggregate.WaitlistOffer", b =>
                {
                    b.HasOne("Shadowbrook.Domain.TeeTimeOpeningAggregate.TeeTimeOpening", null)
                        .WithMany()
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
