// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shadowbrook.Api.Infrastructure.Data;

#nullable disable

namespace Shadowbrook.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311174705_MoveDomainEntitiesToDomainProject")]
    partial class MoveDomainEntitiesToDomainProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shadowbrook.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("GolferName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Date", "Time");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Shadowbrook.Api.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeOnly?>("FirstTeeTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("FlatRatePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("LastTeeTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeeTimeIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("WaitlistEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Shadowbrook.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationName")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Shadowbrook.Domain.Golfers.Golfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Golfers", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.GolferWaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseWaitlistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GolferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWalkUp")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GolferId");

                    b.HasIndex("CourseWaitlistId", "GolferId")
                        .IsUnique()
                        .HasFilter("[RemovedAt] IS NULL");

                    b.ToTable("GolferWaitlistEntries", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.TeeTimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GolfersNeeded")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("TeeTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WalkUpWaitlistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseWaitlistId");

                    b.HasKey("Id");

                    b.HasIndex("WalkUpWaitlistId", "Status")
                        .HasDatabaseName("IX_WaitlistRequests_CourseWaitlistId_Status");

                    b.HasIndex("WalkUpWaitlistId", "TeeTime")
                        .HasDatabaseName("IX_WaitlistRequests_CourseWaitlistId_TeeTime");

                    b.ToTable("WaitlistRequests", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.WalkUpWaitlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Date")
                        .IsUnique();

                    b.HasIndex("ShortCode", "Date");

                    b.ToTable("CourseWaitlists", (string)null);
                });

            modelBuilder.Entity("Shadowbrook.Api.Models.Booking", b =>
                {
                    b.HasOne("Shadowbrook.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Shadowbrook.Api.Models.Course", b =>
                {
                    b.HasOne("Shadowbrook.Api.Models.Tenant", "Tenant")
                        .WithMany("Courses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.GolferWaitlistEntry", b =>
                {
                    b.HasOne("Shadowbrook.Domain.WalkUpWaitlist.WalkUpWaitlist", null)
                        .WithMany("Entries")
                        .HasForeignKey("CourseWaitlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shadowbrook.Domain.Golfers.Golfer", null)
                        .WithMany()
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.TeeTimeRequest", b =>
                {
                    b.HasOne("Shadowbrook.Domain.WalkUpWaitlist.WalkUpWaitlist", null)
                        .WithMany("TeeTimeRequests")
                        .HasForeignKey("WalkUpWaitlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WaitlistRequests_CourseWaitlists_CourseWaitlistId");
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.WalkUpWaitlist", b =>
                {
                    b.HasOne("Shadowbrook.Api.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shadowbrook.Api.Models.Tenant", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Shadowbrook.Domain.WalkUpWaitlist.WalkUpWaitlist", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("TeeTimeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
